# Generated by Django 3.1.7 on 2021-04-06 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fund.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=200)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_category', models.CharField(choices=[('MEDICAL', 'MEDICAL'), ('PHYSICAL HELP', 'PHYSICAL HELP'), ('OTHER', 'OTHER')], default='OTHER', max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('collected', models.FloatField(default=0)),
                ('desc', models.CharField(default='No Description', max_length=200)),
                ('identity_image', models.ImageField(blank=True, null=True, upload_to=fund.models.get_file_address)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=fund.models.get_file_address)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=fund.models.get_file_address)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED')], default='REQUESTED', max_length=50)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_msg', models.CharField(default='none', max_length=200, null=True)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.account')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')], default='PENDING', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.account')),
                ('request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.request')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_fullname', models.CharField(max_length=200)),
                ('admin_phone', models.CharField(max_length=12)),
                ('admin_email', models.CharField(max_length=200)),
                ('admin_username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.account')),
                ('admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.admin')),
                ('request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fund.request')),
            ],
        ),
    ]
